.catalog:
  name: AutoScale
  version: 1.0.0
  description: |
      Auto scale container when condition meet
  
services:
  ubuntu:
    scale: 1
    start_on_create: true
  centos:
    scale: 1
    start_on_create: true
